using UnityEngine;

public enum CardType {
	CLOVER_2, DIAMOND_2, HEART_2, SPADE_2, // 3
	CLOVER_3, DIAMOND_3, HEART_3, SPADE_3, // 7
	CLOVER_4, DIAMOND_4, HEART_4, SPADE_4, // 11
	CLOVER_5, DIAMOND_5, HEART_5, SPADE_5, // 15
	CLOVER_6, DIAMOND_6, HEART_6, SPADE_6, // 19
	CLOVER_7, DIAMOND_7, HEART_7, SPADE_7, // 23
	CLOVER_8, DIAMOND_8, HEART_8, SPADE_8, // 27
	CLOVER_9, DIAMOND_9, HEART_9, SPADE_9, // 31
	CLOVER_10, DIAMOND_10, HEART_10, SPADE_10, // 35
	CLOVER_j, DIAMOND_j, HEART_j, SPADE_j, // 39
	CLOVER_q, DIAMOND_q, HEART_q, SPADE_q, // 43
	CLOVER_k, DIAMOND_k, HEART_k, SPADE_k, // 47
	CLOVER_a, DIAMOND_a, HEART_a, SPADE_a, // 51
}

public class Card {

	public CardType cardType;

}
